config/routes.rb
Simpleblog::Application.routes.draw do

  resources :posts  

  root to: 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
#before_filter :get_post, only: [:edit, :update, :show, :destr]


	def index
		@posts = Post.all
	end

	def show
		@post = get_post
	end

	def edit
		@post = get_post
	end

	def new
		@post = Post.new
	end

	def update
		@post = get_post
		if @post.update_attributes(params[:post]) then redirect_to posts_path else render :edit end
	end

	def create
		@post = Post.new(params[:post])
		if @post.save then redirect_to posts_path else render :new end
	end

	def destroy
		@post = get_post

		unless @post.destroy
			flash[:notice] = "Post could not be deleted"
		end		

		#flash[:notice] = "Post could not be deleted" unless @post.destroy

		redirect_to posts_path
	end

	private 
	def get_post
		Post.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simpleblog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<div>
	<%= form_for @post do |f| %>
<div>
	<%= f.label :title %>
	<%= f.text_field :title %>
</div>
<div>
	<%= f.label :body %>
	<%= f.text_area :body %>
</div>
<%= f.submit %>
<% end %>
</div>

app/views/posts/_post.html.erb
<%= content_tag_for :li, post do %>
	<%= link_to post.title, post_path(post) %>
	<%= link_to "Edit", edit_post_path(post) %> 
	<%= link_to "Delete", post_path(post), method: :delete %>
<% end %>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<h1>All Posts</h1>
<%= link_to "New Post", new_post_path %>
<ul class='posts'>
	<%= render @posts %>
</ul>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<div>
	<%= @post.body %>
</div>